### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by jakubczaplicki** [osrf/osrf.github.io#1]
The website doesn't work right now: http://www.osrfoundation.org/ - "Error establishing a database connection"

**Comment by scpeters** [comment]
Thanks, I restarted the database, and it appears to be up again

**Comment by wjwwood** [comment]
This repository doesn't actually store the website. I think I created it when we were thinking about a static hosting solution, but we ended up with a wordpress based site. I'm gonna delete the repository's content to avoid confusion.

**Comment by jakubczaplicki** [comment]
I know. I didn't know where to report the problem, and this seemed to be the best place.

**Comment by scpeters** [comment]
I think it's fine to report them here.

**Comment by scpeters** [comment]
but I'll defer to @wjwwood

**Comment by wjwwood** [comment]
Feel free to report here, I just remove the content of the repository. The out-of-date static site is in the history and the issue tracker will stay here.

**Comment by wjwwood** [comment]
I don't know if there is a preferable place to report these problems, maybe @gerkey has an idea.

**Comment by gerkey** [comment]
You could also send email to info@osrfoundation.org, but this is as good a place as any to report problems. The more avenues for reporting, the better.
